# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 477cb7c70aeb443db3d347cefdabf8601ca312b118923a65accab40703c9140ef6ba96c50e02ad7011ed3a2bd59d4ceb533ba0d6f398c6e290ec2ce4b7ec10c9

test:
  secret_key_base: d20dd09271e468ac0ceac054267179058e9573e6e58eb40f97ac5dba18721f5394f57c9454538609dd97fe22cfd729fd221132d53d184a4cbfed20df5b58933a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
